spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: ${AZURE_KEY_VAULT_ENDPOINT} # environment variable (All caps seperated by underscores)
  datasource:
    url: ${datasource-url} # secret from Azure key vault
    username: ${datasource-username} # secret from Azure key vault
    password: ${datasource-password} # secret from Azure key vault
  jpa:
    hibernate:
      ddl-auto: none #Turn off DDL auto generation
  ai:
    openai:
      endpoint: ${AI_OPENAI_ENDPOINT:https://api.openai.com/v1/chat/completions}
      api-key: ${AI_OPENAI_API_KEY:YOUR_API_KEY}



