spring:
  datasource:
    url: jdbc:h2:mem:hogwarts
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
  ai:
    openai:
      endpoint: ${AI_OPENAI_ENDPOINT:https://api.openai.com/v1/chat/completions}
      api-key: ${AI_OPENAI_API_KEY:YOUR_API_KEY}


